version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./models:/models
    command: flask run --host=0.0.0.0 --port=8080
    env_file:
      - .env
    container_name: dashboard

  train_model:
    build: .
    volumes:
      - .:/app
      - ./models:/models
    container_name: train_model
